/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/800-000-views-special-model-sdc-0767ad6f75464a3fab9868958625738e
title: 800 000 views - SPECIAL MODEL - SDC
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Object_6: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_31: THREE.Mesh;
    Object_33: THREE.Mesh;
    Object_35: THREE.Mesh;
    Object_37: THREE.Mesh;
    Object_39: THREE.Mesh;
    Object_40: THREE.Mesh;
    Object_41: THREE.Mesh;
    Object_42: THREE.Mesh;
    Object_43: THREE.Mesh;
    Object_44: THREE.Mesh;
    Object_45: THREE.Mesh;
    Object_46: THREE.Mesh;
    Object_48: THREE.Mesh;
    Object_50: THREE.Mesh;
    Object_52: THREE.Mesh;
    Object_54: THREE.Mesh;
    Object_56: THREE.Mesh;
    Object_57: THREE.Mesh;
    Object_59: THREE.Mesh;
    Object_60: THREE.Mesh;
    Object_62: THREE.Mesh;
    Object_63: THREE.Mesh;
    Object_64: THREE.Mesh;
    Object_65: THREE.Mesh;
    Object_67: THREE.Mesh;
    Object_68: THREE.Mesh;
    Object_70: THREE.Mesh;
    Object_71: THREE.Mesh;
    Object_73: THREE.Mesh;
    Object_74: THREE.Mesh;
    Object_76: THREE.Mesh;
    Object_78: THREE.Mesh;
    Object_79: THREE.Mesh;
    Object_81: THREE.Mesh;
    Object_82: THREE.Mesh;
    Object_84: THREE.Mesh;
    Object_86: THREE.Mesh;
    Object_88: THREE.Mesh;
    Object_90: THREE.Mesh;
    Object_92: THREE.Mesh;
    Object_94: THREE.Mesh;
    Object_95: THREE.Mesh;
    Object_97: THREE.Mesh;
    Object_98: THREE.Mesh;
    Object_100: THREE.Mesh;
    Object_101: THREE.Mesh;
    Object_103: THREE.Mesh;
    Object_105: THREE.Mesh;
    Object_107: THREE.Mesh;
    Object_108: THREE.Mesh;
    Object_110: THREE.Mesh;
    Object_112: THREE.Mesh;
    Object_113: THREE.Mesh;
    Object_115: THREE.Mesh;
    Object_117: THREE.Mesh;
    Object_119: THREE.Mesh;
    Object_120: THREE.Mesh;
    Object_121: THREE.Mesh;
    Object_122: THREE.Mesh;
    Object_123: THREE.Mesh;
    Object_124: THREE.Mesh;
    Object_125: THREE.Mesh;
    Object_126: THREE.Mesh;
    Object_127: THREE.Mesh;
    Object_129: THREE.Mesh;
  };
  materials: {
    ['Material.017']: THREE.MeshStandardMaterial;
    ['Material.040']: THREE.MeshStandardMaterial;
    ['Material.041']: THREE.MeshStandardMaterial;
    ['Material.043']: THREE.MeshStandardMaterial;
    ['Material.044']: THREE.MeshStandardMaterial;
    ['Default.001']: THREE.MeshStandardMaterial;
    ['Material.045']: THREE.MeshStandardMaterial;
    ['Material.046']: THREE.MeshStandardMaterial;
    ['Material.077']: THREE.MeshStandardMaterial;
    ['Material.076']: THREE.MeshStandardMaterial;
    ['Material.084']: THREE.MeshStandardMaterial;
    ['Material.085']: THREE.MeshStandardMaterial;
    ['Material.013']: THREE.MeshStandardMaterial;
    Miroir: THREE.MeshStandardMaterial;
    ['Material.001']: THREE.MeshStandardMaterial;
    ['Material.005']: THREE.MeshStandardMaterial;
    ['Material.014']: THREE.MeshStandardMaterial;
    ['Material.019']: THREE.MeshStandardMaterial;
    ['Material.083']: THREE.MeshStandardMaterial;
    ['Material.079']: THREE.MeshStandardMaterial;
    ['Material.081']: THREE.MeshStandardMaterial;
    ['Material.080']: THREE.MeshStandardMaterial;
    ['Material.078']: THREE.MeshStandardMaterial;
    ['Material.007']: THREE.MeshStandardMaterial;
    ['Material.009']: THREE.MeshStandardMaterial;
    ['Material.003']: THREE.MeshStandardMaterial;
    material_0: THREE.MeshStandardMaterial;
    ['Material.012']: THREE.MeshStandardMaterial;
    ['Material.002']: THREE.MeshStandardMaterial;
    ['Material.010']: THREE.MeshStandardMaterial;
    ['Material.008']: THREE.MeshStandardMaterial;
    ['Material.004']: THREE.MeshStandardMaterial;
    ['Material.011']: THREE.MeshStandardMaterial;
    black: THREE.MeshStandardMaterial;
    ['Material.063']: THREE.MeshStandardMaterial;
    ['Material.062']: THREE.MeshStandardMaterial;
    drlwhite: THREE.MeshStandardMaterial;
    xenonhead: THREE.MeshStandardMaterial;
    ['Material.061']: THREE.MeshStandardMaterial;
    ['Material.060']: THREE.MeshStandardMaterial;
    ['Material.059']: THREE.MeshStandardMaterial;
    ['Material.058']: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/lambo.gltf') as any;
  return (
    <group {...props} dispose={null} scale={1.3}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-4.01, -0.07, -0.08]}
            rotation={[0, 0, 0.02]}
            scale={0.03}
          >
            <group rotation={[0, 0, Math.PI / 2]} scale={0.1}>
              <group
                position={[-192.22, -1579.68, 30]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={48.67}
              >
                <mesh
                  geometry={nodes.Object_6.geometry}
                  material={materials['Material.017']}
                />
              </group>
              <group
                position={[-297.24, -1575.53, -648.24]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={69.7}
              >
                <mesh
                  geometry={nodes.Object_8.geometry}
                  material={materials['Material.017']}
                />
              </group>
            </group>
          </group>
          <group rotation={[0, -Math.PI / 2, 0]} scale={0}>
            <mesh
              geometry={nodes.Object_10.geometry}
              material={materials['Material.040']}
            />
            <mesh
              geometry={nodes.Object_11.geometry}
              material={materials['Material.041']}
            />
            <mesh
              geometry={nodes.Object_12.geometry}
              material={materials['Material.043']}
            />
            <mesh
              geometry={nodes.Object_13.geometry}
              material={materials['Material.044']}
            />
            <mesh
              geometry={nodes.Object_14.geometry}
              material={materials['Default.001']}
            />
            <mesh
              geometry={nodes.Object_15.geometry}
              material={materials['Material.045']}
            />
            <mesh
              geometry={nodes.Object_16.geometry}
              material={materials['Material.046']}
            />
            <mesh
              geometry={nodes.Object_17.geometry}
              material={materials['Material.077']}
            />
            <mesh
              geometry={nodes.Object_18.geometry}
              material={materials['Material.076']}
            />
            <mesh
              geometry={nodes.Object_19.geometry}
              material={materials['Material.084']}
            />
            <mesh
              geometry={nodes.Object_20.geometry}
              material={materials['Material.085']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[0, 0, 0.02]}>
            <mesh
              geometry={nodes.Object_22.geometry}
              material={materials['Material.013']}
            />
          </group>
          <group
            position={[0, 0.02, 0]}
            rotation={[Math.PI / 2, 0.02, 0]}
            scale={0.01}
          >
            <mesh
              geometry={nodes.Object_24.geometry}
              material={materials.Miroir}
            />
            <mesh
              geometry={nodes.Object_25.geometry}
              material={materials['Material.001']}
            />
            <mesh
              geometry={nodes.Object_26.geometry}
              material={materials['Material.005']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[0, 0, 0.02]}>
            <mesh
              geometry={nodes.Object_28.geometry}
              material={materials['Material.005']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[0, 0, 0.02]} scale={0.07}>
            <mesh
              geometry={nodes.Object_30.geometry}
              material={materials['Material.005']}
            />
            <mesh
              geometry={nodes.Object_31.geometry}
              material={materials['Material.001']}
            />
          </group>
          <group
            position={[0, 0.02, 0]}
            rotation={[Math.PI / 2, 0.02, 0]}
            scale={0.11}
          >
            <mesh
              geometry={nodes.Object_33.geometry}
              material={materials['Material.014']}
            />
          </group>
          <group
            position={[0.01, -0.67, 0.27]}
            rotation={[Math.PI, 0, 3.12]}
            scale={0}
          >
            <mesh
              geometry={nodes.Object_35.geometry}
              material={materials['Material.046']}
            />
          </group>
          <group
            position={[0.01, -0.29, -2.43]}
            rotation={[-1.57, 1.55, 2.47]}
            scale={2.76}
          >
            <mesh
              geometry={nodes.Object_37.geometry}
              material={materials['Material.019']}
            />
          </group>
          <group rotation={[0, -Math.PI / 2, 0]} scale={0}>
            <mesh
              geometry={nodes.Object_39.geometry}
              material={materials['Material.076']}
            />
            <mesh
              geometry={nodes.Object_40.geometry}
              material={materials['Material.041']}
            />
            <mesh
              geometry={nodes.Object_41.geometry}
              material={materials['Material.043']}
            />
            <mesh
              geometry={nodes.Object_42.geometry}
              material={materials['Material.044']}
            />
            <mesh
              geometry={nodes.Object_43.geometry}
              material={materials['Default.001']}
            />
            <mesh
              geometry={nodes.Object_44.geometry}
              material={materials['Material.046']}
            />
            <mesh
              geometry={nodes.Object_45.geometry}
              material={materials['Material.077']}
            />
            <mesh
              geometry={nodes.Object_46.geometry}
              material={materials['Material.083']}
            />
          </group>
          <group
            position={[3.79, 0.84, 2.7]}
            rotation={[Math.PI / 2, 0, 2.83]}
            scale={1.19}
          >
            <mesh
              geometry={nodes.Object_48.geometry}
              material={materials['Material.079']}
            />
          </group>
          <group
            position={[3.84, 0.84, 2.85]}
            rotation={[Math.PI / 2, 0, 2.83]}
            scale={1.19}
          >
            <mesh
              geometry={nodes.Object_50.geometry}
              material={materials['Material.081']}
            />
          </group>
          <group
            position={[3.82, 0.84, 2.78]}
            rotation={[Math.PI / 2, 0, 2.83]}
            scale={1.19}
          >
            <mesh
              geometry={nodes.Object_52.geometry}
              material={materials['Material.080']}
            />
          </group>
          <group
            position={[0, -0.74, 0]}
            rotation={[0, 0.22, 0]}
            scale={[3.8, 1.43, 7.42]}
          >
            <mesh
              geometry={nodes.Object_54.geometry}
              material={materials['Material.078']}
            />
          </group>
          <group rotation={[0, -Math.PI / 2, 0]} scale={0}>
            <mesh
              geometry={nodes.Object_56.geometry}
              material={materials['Material.084']}
            />
            <mesh
              geometry={nodes.Object_57.geometry}
              material={materials['Material.085']}
            />
          </group>
          <group
            position={[2.66, 0, 0]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0}
          >
            <mesh
              geometry={nodes.Object_59.geometry}
              material={materials['Material.084']}
            />
            <mesh
              geometry={nodes.Object_60.geometry}
              material={materials['Material.085']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh
              geometry={nodes.Object_62.geometry}
              material={materials['Material.001']}
            />
            <mesh
              geometry={nodes.Object_63.geometry}
              material={materials['Material.005']}
            />
            <mesh
              geometry={nodes.Object_64.geometry}
              material={materials['Material.007']}
            />
            <mesh
              geometry={nodes.Object_65.geometry}
              material={materials['Material.009']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh
              geometry={nodes.Object_67.geometry}
              material={materials['Material.003']}
            />
            <mesh
              geometry={nodes.Object_68.geometry}
              material={materials.material_0}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh
              geometry={nodes.Object_70.geometry}
              material={materials['Material.005']}
            />
            <mesh
              geometry={nodes.Object_71.geometry}
              material={materials['Material.046']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh
              geometry={nodes.Object_73.geometry}
              material={materials['Material.005']}
            />
            <mesh
              geometry={nodes.Object_74.geometry}
              material={materials['Material.046']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh
              geometry={nodes.Object_76.geometry}
              material={materials['Material.012']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh
              geometry={nodes.Object_78.geometry}
              material={materials['Material.002']}
            />
            <mesh
              geometry={nodes.Object_79.geometry}
              material={materials['Material.012']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh
              geometry={nodes.Object_81.geometry}
              material={materials['Material.001']}
            />
            <mesh
              geometry={nodes.Object_82.geometry}
              material={materials['Material.010']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh
              geometry={nodes.Object_84.geometry}
              material={materials['Material.005']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh
              geometry={nodes.Object_86.geometry}
              material={materials['Material.001']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh
              geometry={nodes.Object_88.geometry}
              material={materials['Material.005']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh
              geometry={nodes.Object_90.geometry}
              material={materials['Material.002']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh
              geometry={nodes.Object_92.geometry}
              material={materials['Material.005']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh
              geometry={nodes.Object_94.geometry}
              material={materials['Material.001']}
            />
            <mesh
              geometry={nodes.Object_95.geometry}
              material={materials['Material.005']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh
              geometry={nodes.Object_97.geometry}
              material={materials['Material.003']}
            />
            <mesh
              geometry={nodes.Object_98.geometry}
              material={materials['Material.001']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh
              geometry={nodes.Object_100.geometry}
              material={materials['Material.002']}
            />
            <mesh
              geometry={nodes.Object_101.geometry}
              material={materials['Material.008']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh
              geometry={nodes.Object_103.geometry}
              material={materials['Material.002']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh
              geometry={nodes.Object_105.geometry}
              material={materials['Material.012']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh
              geometry={nodes.Object_107.geometry}
              material={materials['Material.002']}
            />
            <mesh
              geometry={nodes.Object_108.geometry}
              material={materials['Material.008']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh
              geometry={nodes.Object_110.geometry}
              material={materials['Material.002']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh
              geometry={nodes.Object_112.geometry}
              material={materials['Material.005']}
            />
            <mesh
              geometry={nodes.Object_113.geometry}
              material={materials['Material.041']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh
              geometry={nodes.Object_115.geometry}
              material={materials['Material.004']}
            />
          </group>
          <group
            position={[0, 0.11, 1.2]}
            rotation={[0, 0, 0.02]}
            scale={[0.56, 1, 1]}
          >
            <mesh
              geometry={nodes.Object_117.geometry}
              material={materials['Material.011']}
            />
          </group>
          <group
            position={[0.01, -0.46, -0.57]}
            rotation={[Math.PI / 2, 0.02, Math.PI]}
            scale={0.63}
          >
            <mesh
              geometry={nodes.Object_119.geometry}
              material={materials.black}
            />
            <mesh
              geometry={nodes.Object_120.geometry}
              material={materials['Material.063']}
            />
            <mesh
              geometry={nodes.Object_121.geometry}
              material={materials['Material.062']}
            />
            <mesh
              geometry={nodes.Object_122.geometry}
              material={materials.drlwhite}
            />
            <mesh
              geometry={nodes.Object_123.geometry}
              material={materials.xenonhead}
            />
            <mesh
              geometry={nodes.Object_124.geometry}
              material={materials['Material.061']}
            />
            <mesh
              geometry={nodes.Object_125.geometry}
              material={materials['Material.060']}
            />
            <mesh
              geometry={nodes.Object_126.geometry}
              material={materials['Material.059']}
            />
            <mesh
              geometry={nodes.Object_127.geometry}
              material={materials['Material.058']}
            />
          </group>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0.02, 0]}>
            <mesh
              geometry={nodes.Object_129.geometry}
              material={materials['Material.001']}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/lambo.gltf');
