export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const SET_USER = 'SET_USER';

export const GITHUB_SIGN_IN_START = 'GITHUB_SIGN_IN_START';
export const GITHUB_SIGN_IN_SUCCESS = 'GITHUB_SIGN_IN_SUCCESS';
export const GITHUB_SIGN_IN_FAIL = 'GITHUB_SIGN_IN_FAIL';
